sudo: required

services:
  - docker

before_install:
  - docker build -t andreidincu/react-test -f ./client/Dockerfile.dev ./client

scrip:
  - docker run -e CI=true andreidincu/react-test npm test -- --coverage

after_success:
  - docker build -t andreidincu/multi-client ./client
  - docker build -t andreidincu/multi-server ./server
  - docker build -t andreidincu/multi-nginx ./nginx
  - docker build -t andreidincu/multi-worker ./worker
# Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
  - docker push andreidincu/multi-client
  - docker push andreidincu/multi-server
  - docker push andreidincu/multi-nginx
  - docker push andreidincu/multi-worker
